"""Diagnostics 2.0 limits and schema identifiers."""

from __future__ import annotations

DIAGNOSTIC_SCHEMA_VERSION = 1
SUPPORT_BUNDLE_SCHEMA_VERSION = 1

MAX_EVENT_BUFFER_ENTRIES = 500
MAX_EXPORTED_EVENTS = 400
MAX_BUNDLE_BYTES = 5 * 1024 * 1024
MAX_LOG_TAIL_BYTES = 256 * 1024
VERBOSE_DEFAULT_SECONDS = 15 * 60
