from __future__ import annotations

from exilelens.error_catalog.definitions import (
    ErrorCategory,
    ErrorSeverity,
    Retryability,
    StructuredErrorDefinition,
)

# Authoritative EL-* registry. One code per distinct user-facing failure class.
_ERROR_ENTRIES: tuple[StructuredErrorDefinition, ...] = (
    StructuredErrorDefinition(
        "EL-APP-001",
        ErrorCategory.APPLICATION,
        ErrorSeverity.CRITICAL,
        "ExileLens could not start",
        "A required component failed while ExileLens was starting.",
        "Restart ExileLens. If this repeats, copy diagnostics and report an issue.",
        Retryability.USER_ACTION,
        ("stage", "engine_code"),
    ),
    StructuredErrorDefinition(
        "EL-POB-001",
        ErrorCategory.PATH_OF_BUILDING,
        ErrorSeverity.ERROR,
        "Path of Building not found",
        "ExileLens cannot find a valid Path of Building installation folder.",
        "Choose your Path of Building installation in Settings.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-POB-002",
        ErrorCategory.PATH_OF_BUILDING,
        ErrorSeverity.ERROR,
        "Path of Building failed to start",
        "ExileLens could not start the Path of Building calculation engine.",
        "Verify the PoB folder, then reconnect from Settings or the tray.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-POB-003",
        ErrorCategory.PATH_OF_BUILDING,
        ErrorSeverity.ERROR,
        "Unsupported Path of Building version",
        "This Path of Building build is not compatible with ExileLens.",
        "Install a supported Path of Building Community (PoE2) release.",
        Retryability.NONE,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-POB-004",
        ErrorCategory.PATH_OF_BUILDING,
        ErrorSeverity.WARNING,
        "Path of Building loadouts unavailable",
        "This Path of Building build does not expose the loadout API ExileLens expects.",
        "Update Path of Building or continue without loadout switching.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-BLD-001",
        ErrorCategory.BUILD,
        ErrorSeverity.ERROR,
        "Build file not found",
        "The selected build file does not exist on disk.",
        "Select another build file in Settings.",
        Retryability.USER_ACTION,
        ("engine_code", "build_path"),
    ),
    StructuredErrorDefinition(
        "EL-BLD-002",
        ErrorCategory.BUILD,
        ErrorSeverity.ERROR,
        "Build could not be loaded",
        "Path of Building rejected the build file.",
        "Open the build in Path of Building, save it, then reload in ExileLens.",
        Retryability.USER_ACTION,
        ("engine_code", "build_path"),
    ),
    StructuredErrorDefinition(
        "EL-BLD-003",
        ErrorCategory.BUILD,
        ErrorSeverity.WARNING,
        "Build file incomplete",
        "The build file looks incomplete, for example if Path of Building was mid-save.",
        "Save the build in Path of Building, then reload it in ExileLens.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-BLD-004",
        ErrorCategory.BUILD,
        ErrorSeverity.WARNING,
        "No build loaded",
        "Item Check needs an active build before it can compare items.",
        "Select a build in Settings or the tray menu.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-BLD-005",
        ErrorCategory.BUILD,
        ErrorSeverity.WARNING,
        "Build changed during evaluation",
        "The loaded build changed while an item was being evaluated.",
        "Copy the item again after the build finishes loading.",
        Retryability.USER_ACTION,
        ("stage",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-001",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.ERROR,
        "Item could not be parsed",
        "The copied item text could not be interpreted as a valid item.",
        "Copy the item again from the game with the correct tooltip.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-002",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.WARNING,
        "Item incompatible",
        "This item cannot be evaluated against the current build context.",
        "Check that the correct build and slot are active.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-003",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.INFO,
        "Not a Path of Exile 2 item",
        "The clipboard does not contain a PoE 2 item tooltip.",
        "Hover an item in-game and copy it before using Item Check.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-004",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.WARNING,
        "Unsupported item",
        "This item type is not supported for automated comparison yet.",
        "Try another item or compare manually in Path of Building.",
        Retryability.NONE,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-005",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.ERROR,
        "Invalid equipment slot",
        "The item could not be placed in a valid equipment slot for this build.",
        "Verify the build and item class, then try again.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-006",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.ERROR,
        "Slot could not be resolved",
        "ExileLens could not determine which slot to compare.",
        "Copy the item again or pick a compatible slot in Path of Building.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-007",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.WARNING,
        "Ambiguous equipment slot",
        "More than one slot could fit this item.",
        "Equip the baseline item in Path of Building, then try again.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-008",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.WARNING,
        "No compatible slot",
        "This item does not fit any slot on the current build.",
        "Check the build or try a different item.",
        Retryability.NONE,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-009",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.ERROR,
        "Build not ready for evaluation",
        "The build is not in a state that supports Item Check.",
        "Wait for the build to finish loading or reload it from Settings.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-010",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.WARNING,
        "Primary metric unresolved",
        "ExileLens could not identify the main comparison metric for this check.",
        "Verify the build's main skill setup in Path of Building.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-011",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.WARNING,
        "Baseline item unresolved",
        "No baseline item was available for comparison in the selected slot.",
        "Equip a baseline item in Path of Building, then copy the candidate again.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-012",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.ERROR,
        "Build restore failed",
        "Path of Building could not restore the build after the comparison.",
        "Reload the build from Settings and run Item Check again.",
        Retryability.USER_ACTION,
        ("engine_code",),
    ),
    StructuredErrorDefinition(
        "EL-CHK-013",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.ERROR,
        "Item Check calculation failed",
        "Path of Building returned an error while evaluating this item.",
        "Try again. If it persists, reload the build or restart the calculation engine.",
        Retryability.USER_ACTION,
        ("engine_code", "stage"),
    ),
    StructuredErrorDefinition(
        "EL-CHK-014",
        ErrorCategory.ITEM_CHECK,
        ErrorSeverity.ERROR,
        "Item Check presentation failed",
        "The evaluation finished but ExileLens could not display the result.",
        "Copy the item again. Copy diagnostics if the problem continues.",
        Retryability.USER_ACTION,
        ("stage",),
    ),
    StructuredErrorDefinition(
        "EL-WRK-001",
        ErrorCategory.WORKER,
        ErrorSeverity.ERROR,
        "Calculation worker unavailable",
        "ExileLens lost its connection to the Path of Building worker.",
        "Reconnect or restart the calculation engine from the tray.",
        Retryability.USER_ACTION,
        ("engine_code", "stage"),
    ),
    StructuredErrorDefinition(
        "EL-WRK-002",
        ErrorCategory.WORKER,
        ErrorSeverity.ERROR,
        "Calculation worker stopped",
        "The worker stopped before your analysis could finish.",
        "Try Item Check again or reload the build.",
        Retryability.USER_ACTION,
        ("stage",),
    ),
    StructuredErrorDefinition(
        "EL-KEY-001",
        ErrorCategory.HOTKEY_CLIPBOARD,
        ErrorSeverity.INFO,
        "Unsupported game language",
        "Item Check requires English item tooltips from the game client.",
        "Switch Path of Exile 2 to English, then copy the item again.",
        Retryability.USER_ACTION,
        ("language_code", "confidence"),
    ),
    StructuredErrorDefinition(
        "EL-UI-001",
        ErrorCategory.USER_INTERFACE,
        ErrorSeverity.ERROR,
        "Overlay could not show the result",
        "The Item Check overlay failed while presenting information.",
        "Try Item Check again or open Diagnostics for details.",
        Retryability.USER_ACTION,
        ("stage",),
    ),
    StructuredErrorDefinition(
        "EL-UPD-001",
        ErrorCategory.UPDATE,
        ErrorSeverity.ERROR,
        "Update verification failed",
        "A newer release is listed but its signed update metadata could not be verified.",
        "Do not install manually from untrusted sources. Try Check for updates again later.",
        Retryability.USER_ACTION,
        ("remote_version",),
    ),
    StructuredErrorDefinition(
        "EL-UPD-002",
        ErrorCategory.UPDATE,
        ErrorSeverity.ERROR,
        "Update download failed verification",
        "The downloaded update package did not match the signed manifest.",
        "Cancel the download and run Check for updates again.",
        Retryability.USER_ACTION,
        ("reason",),
    ),
    StructuredErrorDefinition(
        "EL-UPD-003",
        ErrorCategory.UPDATE,
        ErrorSeverity.WARNING,
        "Update check failed",
        "ExileLens could not reach GitHub to check for updates.",
        "Check your network connection and try again from Settings.",
        Retryability.USER_ACTION,
        (),
    ),
    StructuredErrorDefinition(
        "EL-DIAG-001",
        ErrorCategory.DIAGNOSTICS,
        ErrorSeverity.WARNING,
        "Support package export failed",
        "ExileLens could not build the support package.",
        "Try Export support package again or use Copy diagnostics.",
        Retryability.USER_ACTION,
        ("reason",),
    ),
    StructuredErrorDefinition(
        "EL-APP-099",
        ErrorCategory.APPLICATION,
        ErrorSeverity.ERROR,
        "Unexpected error",
        "An unrecognized error occurred inside ExileLens.",
        "Try the suggested recovery action. Copy diagnostics if it continues.",
        Retryability.USER_ACTION,
        ("exception_type",),
    ),
)

ERROR_REGISTRY: dict[str, StructuredErrorDefinition] = {row.code: row for row in _ERROR_ENTRIES}

_ENGINE_CODE_TO_EL: dict[str, str] = {
    "POB_PATH_INVALID": "EL-POB-001",
    "POB_BOOT_FAILED": "EL-POB-002",
    "UNSUPPORTED_POB_REVISION": "EL-POB-003",
    "POB_LOADOUT_API_UNSUPPORTED": "EL-POB-004",
    "BUILD_NOT_FOUND": "EL-BLD-001",
    "BUILD_PARSE_FAILED": "EL-BLD-002",
    "BUILD_SOURCE_INCOMPLETE": "EL-BLD-003",
    "NO_BUILD_LOADED": "EL-BLD-004",
    "STALE_BUILD_GENERATION": "EL-BLD-005",
    "ITEM_PARSE_FAILED": "EL-CHK-001",
    "ITEM_INCOMPATIBLE": "EL-CHK-002",
    "NOT_POE2_ITEM": "EL-CHK-003",
    "ITEM_UNSUPPORTED": "EL-CHK-004",
    "SLOT_INVALID": "EL-CHK-005",
    "SLOT_RESOLUTION_FAILED": "EL-CHK-006",
    "SLOT_RESOLUTION_AMBIGUOUS": "EL-CHK-007",
    "NO_COMPATIBLE_SLOT": "EL-CHK-008",
    "EVALUATION_INVALID_BUILD_STATE": "EL-CHK-009",
    "PRIMARY_METRIC_UNRESOLVED": "EL-CHK-010",
    "BASELINE_ITEM_UNRESOLVED": "EL-CHK-011",
    "RESTORE_FAILED": "EL-CHK-012",
    "CALC_FAILED": "EL-CHK-013",
    "WORKER_UNHEALTHY": "EL-WRK-001",
    "UNSUPPORTED_GAME_LANGUAGE": "EL-KEY-001",
}


def get_error_definition(code: str) -> StructuredErrorDefinition | None:
    return ERROR_REGISTRY.get(str(code or "").strip())


def engine_code_to_el(engine_code: str) -> str:
    return _ENGINE_CODE_TO_EL.get(str(engine_code or "").strip(), "EL-APP-099")


def all_error_codes() -> list[str]:
    return sorted(ERROR_REGISTRY)
