"""Regenerate docs/AMMO-01-GEM-EFFECT-AUDIT.md from the local PoB runtime (AMMO-01 validation evidence).

Everything in the report is derived from PoB: the gem/effect inventory from the bridge's read-only
``describe_gem_effects``, the offense numbers from PoB calculations in six real build contexts, the weapon-sensitivity
table from PoB with the fired effect selected in the build file. No skill-name list and no damage model live here.

    python scripts/audit_gem_effects.py            # needs a local PoB2 runtime (POB2_PATH or the standard install)
"""

from __future__ import annotations

import sys
import tempfile
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from exilelens.config import PobConfig, detect_common_pob_installation, validate_pob_path  # noqa: E402
from exilelens.engine import Engine  # noqa: E402
from exilelens.items.evaluation import evaluate_item  # noqa: E402
from tests import gem_effect_audit as audit  # noqa: E402
from tests.integration.test_ammo01_permafrost_bolts_weapon import BUILD, CANDIDATE  # noqa: E402

OUT = ROOT / "docs" / "AMMO-01-GEM-EFFECT-AUDIT.md"


def _pct(value) -> str:
    return "n/a" if value is None else f"{value:+.1f}%"


def main() -> int:
    import os

    explicit = os.environ.get("POB2_PATH", "").strip()
    path = Path(explicit).expanduser().resolve() if explicit else detect_common_pob_installation()
    if path is None:
        print("no local PoB2 runtime found", file=sys.stderr)
        return 2
    config = PobConfig(path)
    validate_pob_path(config)
    with tempfile.TemporaryDirectory() as scratch, Engine(config, use_subprocess=True) as engine:
        scratch_dir = Path(scratch)
        gems = engine._call("describe_gem_effects", {})["gems"]
        ammo = audit.ammo_gems(gems)
        mappings = [audit.ammo_mapping(g) for g in ammo]
        matrix = audit.weapon_sensitivity_matrix(engine, evaluate_item, ammo, BUILD, CANDIDATE, scratch_dir)
        rows_by_context = {
            name: audit.measure_gem_effects(engine, ROOT / relative, gems, scratch_dir) for name, relative in audit.AUDIT_CONTEXTS
        }
    table = audit.classify_all(gems, rows_by_context)
    counts = Counter(row["class"] for row in table)

    lines = [
        "# AMMO-01 — PoB gem/effect audit (machine-derived)",
        "",
        "Generated by `scripts/audit_gem_effects.py` from the local PoB runtime. Nothing here is a hand-written skill list.",
        "",
        f"* gems granting more than one effect, plus every ammo gem: **{len(gems)}**",
        f"* gems granting a `CrossbowAmmoSkill` effect: **{len(ammo)}** "
        f"({sum(m['status'] == 'DETERMINISTIC' for m in mappings)} map deterministically)",
        f"* audit contexts: {', '.join(name for name, _ in audit.AUDIT_CONTEXTS)}",
        f"* family classes: {', '.join(f'{k}: {counts[k]}' for k in sorted(counts))}",
        "",
        "## 1. Crossbow ammo family: load effect -> fired effect",
        "",
        "| Gem | Load effect (index) | Fired effect (index) | Load stat set(s) | Fired stat set(s) | Fired damage flags | Status |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for m in sorted(mappings, key=lambda m: m["name"]):
        lines.append(
            f"| {m['name']} | {m['load_effect']} ({m['load_index']}) | {m['fired_effect']} ({m['fired_index']}) | "
            f"{', '.join(m['load_stat_sets'])} | {', '.join(m['fired_stat_sets'])} | {', '.join(m['fired_damage_flags'])} | {m['status']} |"
        )
    lines += [
        "",
        "## 2. Weapon sensitivity (PoB is the oracle)",
        "",
        "ExileLens is run end to end on the build that saves the **load** action, with the three perturbations applied together. "
        "The PoB columns are the same build with the **fired** effect saved in the file, read directly for each perturbation. "
        "`equal` means every compared PoB field of ExileLens equals PoB's own.",
        "",
        "| Gem | PoB: flat elemental | PoB: attack speed | PoB: +skill levels | PoB: all | ExileLens: all | Delta kind | Verdict | equal |",
        "| --- | ---: | ---: | ---: | ---: | ---: | --- | --- | --- |",
    ]
    for row in sorted(matrix, key=lambda r: r["gem"]):
        d = row["pob_delta_pct"]
        lines.append(
            f"| {row['gem']} | {_pct(d['flat-elemental'])} | {_pct(d['attack-speed'])} | {_pct(d['skill-level'])} | {_pct(d['all'])} | "
            f"{_pct(row['exilelens_delta_pct'])} | {row['delta_kind']} | {row['verdict']} | {'yes' if row['fields_equal'] else 'NO'} |"
        )
    lines += [
        "",
        "## 3. Multi-effect families (every gem granting more than one effect)",
        "",
        "Classes: **A** safe with the current resolver; **B** declared non-damaging and correctly refused by the truthfulness gate; "
        "**C** potentially vulnerable (a declared non-damaging effect PoB gives offense for that the runtime would still treat as a "
        "damage target); **D** needs dedicated mechanics (several damage-capable siblings, nothing to pair with); **E** intentionally "
        "measurable despite the flag. Only families with a declared non-damaging selectable effect are listed; the rest are class A.",
        "",
        audit.render_markdown(table, rows_by_context.keys()),
    ]
    guard_only = [row for row in table if row.get("guard_only")]
    lines += [
        "## 4. Non-ammo phantoms refused only by the damage-target guard",
        "",
        "Effects PoB declares as dealing no damage yet reports weapon-dependent offense for. Without the guard they would be "
        "measured with high confidence exactly like the ammo load action.",
        "",
    ]
    if guard_only:
        for row in guard_only:
            lines.append(f"* {row['gem']}: {', '.join(row['guard_only'])}")
    else:
        lines.append("* none")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
